### ISSUE TITLE
Feedback for “Smart Contract Overview”

### ISSUE THREAD

**Issue by Sabnock01** [ethereum-optimism/docs#426]
Page is out of data / non-comprehensive. Should include all contracts in [Contract Addresses](https://docs.optimism.io/chain/addresses). Should also probably be moved out of the OP Stack documentation and into OP Mainnet with Contract Addresses or vice versa.

**Comment by sbvegan** [comment]
Yup good call. However I'm in favor of keeping it the OP Stack section because the contracts will be common across OP Stack forks. Where the "Contract Addresses" are specific to OP Mainnet.

**Comment by sbvegan** [comment]
When this page is updated we should also add the following notes:

- We recommend against using the `L2ToL1MessagePasser` directly. Otherwise those that do have their finalized withdrawals being one-shot and can't be replayed if it runs out of gas.
- Bridge contracts are layered over the messengers.
- The main concern with using the optimism portal directly is gas estimation. The cross domain messenger has replay protection baked in to gracefully handle messages that run out of gas.

They probably need to be word smithed, but the general information should make it into the docs.

**Comment by sbvegan** [comment]
Updated here with the all the L1 and L2 contract details. Also added a comprehensive changelog over the L1 release versions: https://docs.optimism.io/stack/smart-contracts

The contract addresses will go into Superchain Registry Work
