### ISSUE TITLE
[TUTORIAL] Docs tutorials out of sync on/after v1.7.0

### ISSUE THREAD

**Issue by astro44** [ethereum-optimism/docs#549]
Please update docs to reflect latest changes in new builds.
since version 1.7.0 hardhat artifacts are no longer used in a few places in the build / run process:
https://github.com/ethereum-optimism/optimism/commit/082d075dcef809ebb940129ff17de8b0f5ec3451
main.go call will need to be changed... currently in the tutorial:
<img width="849" alt="image" src="https://github.com/ethereum-optimism/docs/assets/982747/f933b325-9792-4831-bffe-24e750a77373">

but should look more like:
go run cmd/main.go genesis l2 \
    --deploy-config ../packages/contracts-bedrock/deploy-config/getting-started.json \
    --l1-deployments ../packages/contracts-bedrock/deployments/getting-started/.deploy \
    --outfile.l2 genesis.json \
    --outfile.rollup rollup.json \
    --l1-rpc $L1_RPC_URL
    
also any references to json files in getting-started should likely require the contents of .deploy.
so for running proposer:
<img width="869" alt="image" src="https://github.com/ethereum-optimism/docs/assets/982747/4ecd0692-5b21-43ea-81a9-336f0e7954b7">

should look more like:
for -l2oo-address...  in ()
cat ../packages/contracts-bedrock/deployments/getting-started/.deploy | jq -r '.L2OutputOracleProxy'

and also:
<img width="788" alt="image" src="https://github.com/ethereum-optimism/docs/assets/982747/ee477659-c118-4f33-ab31-d4775ad1c19e">

again... we'll find the address in the .deploy file mentioned above.

**Comment by sbvegan** [comment]
@astro44 was this done on the `tutorials/chain` branch?

https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#build-the-optimism-monorepo

**Comment by luleigreat** [comment]
> @astro44 was this done on the `tutorials/chain` branch?
> 
> https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#build-the-optimism-monorepo

I found the same problem, this was not done on `tutorials/chan` branch，it was on v1.7.0, I think the `tutorials/chan` branch should be upgraded to v1.7.0 ,and also the documents.

I think the `tutorials/chan` branch should keep up with the latest stable version. 

On v1.7.0 branch ,there are several points not consistent with the current `tutorials/chain` branch:
1. When deploy contracts on L1, we just need the the deploy step,and no need the "sync()" step any more
2. When generating the genesis and rollup files, we should use `--l1-deployments ../packages/contracts-bedrock/deployments/getting-started/.deploy` instead of  `--deployment-dir`
3. When start op-node, we should add the `--l1.beacon=xxx`
4. When running the op-proposer, should change the way to get `--l2oo-address`,like `--l2oo-address= $(cat ../packages/contracts-bedrock/deployments/getting-started/.deploy | jq -r '.L2OutputOracleProxy')`

**Comment by luleigreat** [comment]
> @astro44 was this done on the `tutorials/chain` branch?
> 
> https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#build-the-optimism-monorepo

I have another question:

I think the contracts on branch `op-contracts/xxx` was audited, right ?
How about the contracts on branch `tutorials/chain` ?

**Comment by robertacolvin** [comment]
Sorry @luleigreat, @sbvegan somehow didn't see this thread,
I didn't actually make any changes so this isn't on any branch, I just made the "suggestion" here in the ticket.
@luleigreat:
I don't know if they were audited, I would assume so.... but thats a question for someone within Optimisim to answer... maybe @sbvegan can help?

**Comment by astro44** [comment]
Sorry @luleigreat, @sbvegan somehow didn't see this thread,
I didn't actually make any changes so this isn't on any branch, I just made the "suggestion" here in the ticket.
@luleigreat:
I don't know if they were audited, I would assume so.... but thats a question for someone within Optimisim to answer... maybe @sbvegan can help?

**Comment by sbvegan** [comment]
closing in favor of https://github.com/ethereum-optimism/docs/issues/917
