### ISSUE TITLE
[DOCS] Add callout on the cap for sequencer.l1-confs and verifier.l1-confs

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#563]
## Brief Description of the Docs Request

Add a callout to the sequencer.l1-confs and verifier.l1-confs for the max values. Can't be higher than the sequencer drift which is set to 10 minutes.

## Description of the Documentation You'd Like
Explain what the final documentation page or pages should look like. Do you need a guide, tutorial, FAQ, troubleshooting page or more than one page? Do you have any source/content information to provide for the requested page(s)?

## Links to Related Pages
Provide links to any related content pages for this documentation request. This will help us to determine where the page(s) from your docs request should live  
(e.g. a new node operators resource will likely link to other pages in the node operators section of the docs).

## Additional Context

Probably need to loop in eng for specifics

**Comment by cpengilly** [comment]
pinged an engineer in slack for details/confimation

**Comment by cpengilly** [comment]
eng answer: 
- verifier L1 confs does not have a limit, but suggested to be no more than 12-13 minutes. Realistic limit is 10-20 blocks
- sequencer L1 confs has a current limit of 600s / 50 blocks. In Fjord we will increase this to 1800s / 150 blocks. The reason is that otherwise it won’t produce blocks inside the sequence window
