### ISSUE TITLE
[DOCS] mark the legacy contracts

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#578]
## Brief Description of the Docs Request

Mark the legacy contracts in the OP Mainnet contract address page.

## Description of the Documentation You'd Like
Explain what the final documentation page or pages should look like. Do you need a guide, tutorial, FAQ, troubleshooting page or more than one page? Do you have any source/content information to provide for the requested page(s)?

## Links to Related Pages

https://docs.optimism.io/chain/addresses

## Additional Context
Provide any additional context about this documentation request. What problems did you run into that caused you to make this request? 
Which existing documentation pages did you already try as a solution to your problem? Why do you think the requested page(s) will be beneficial to developers in the Optimism Collective?

**Comment by cpengilly** [comment]
@sbvegan I only see a few legacy contracts (with 'legacy' in the title). Are there others? Also, since this page is autogenerated from superchain registry, we wouldnt' be able to mark these on our end. We'd need to put in a request to that team to add it on their side (so it auto-populates in the docs)

**Comment by cpengilly** [comment]
@smartcontracts FV

**Comment by cpengilly** [comment]
pinged an engineer for confirmation/context
